title: portfolio
description: #

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dojj.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
hightlighter: pygments

# root: /portfolio


permalink: :title.html
